---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp-deployment-loadbalancer
 labels:
  app: myapp-app-loadbalancer
spec:
 replicas: 1
 selector:
  matchLabels:
   app: myapp-app-loadbalancer
 template:
  metadata: 
   labels:
    app: myapp-app-loadbalancer
  spec:
   containers:
   - name: myapp-app-loadbalancer
     image: katara123/devops:tagversion
     ports:
     - containerPort: 8080

